[run]
# equivalent to `bun --bun` for all `bun run` commands. https://bun.com/docs/runtime/bunfig#run-bun-auto-alias-node-to-bun
bun = true
# Number of lines of script output shown when using --filter (default: 10). Set to 0 to show all lines. https://bun.com/docs/runtime#param-elide-lines
# elide-lines = 0
# elideLines = 0
