emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/../src/generated"
    output-file: "openapi.yaml"

linter:
  extends:
    - "@typespec/http/recommended"
